[project]
name = "leaderboards"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2",
]

[dependency-groups]
dev = [
    "pytest-django>=4.11.1",
]
